@echo off
echo Starting CodeVail Interview Platform...
echo.
echo Starting Next.js development server...
start "Next.js Server" cmd /c "npm run dev"
echo.
echo Waiting for server to start...
timeout /t 5 /nobreak > nul
echo.
echo Starting Electron app...
npm run electron
pause
